# Generated by Django 4.0.4 on 2022-07-08 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('item', models.CharField(max_length=100, verbose_name='Товар')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('type', models.CharField(max_length=100, verbose_name='Тип(касса/закупка)')),
                ('worker', models.ForeignKey(default='Удален', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
        ),
    ]
