# Generated by Django 4.0.4 on 2022-07-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_cash_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='worker',
        ),
    ]
