# Generated by Django 4.0.4 on 2022-07-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_cash_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='beznal',
            field=models.BooleanField(default=False, verbose_name='Безналичный рассчет'),
        ),
    ]
